jobs:
  compile:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: suleohis/curl@v3
        with: 
            image: ghcr.io/aad-for-linux/pam_aad:ubuntu
            run: |
                 make