

name: CI

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  compile:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
            image: ghcr.io/aad-for-linux/pam_aad:ubuntu
            run: clang -g -Wall curlTest.c -o curlTest -lcurl
